routes/dashboard.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('dashboard')->user();

    // dd($users);

    return view('admin.dashboard');
})->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/', function () {
//     return view('welcome');
// });


// Route::get('/search/{search}',function($search){
// 	return App\Hospital::where('hname','like','%'.$search.'%')->pluck('hname')->toArray();
// });




// //doctor
// Route::get('/doctor', function () {
//     return view('admin.doctor.create');
// });
// Route::get('/doctor/edit', function () {
//     return view('admin.doctor.edit');
// });

// //
// //hospital

// Route::get('/hospital', function () {
//     return view('admin.hospital.create');
// });
// Route::get('/hospital/edit', function () {
//     return view('admin.hospital.edit');
// });
// use Illuminate\Support\Facades\Auth;

// //auth routes
// Auth::routes();


Route::group(['prefix'=>'dashboard', 'middleware'=>'dashboard', 'namespace'=>'Admin'], function(){
    

  Route::get('/', 'DashboardController@index')->name('admin.dashboard');

  // Route::resource('categories', 'CategoryController');

  Route::resource('user', 'UserController');
  Route::get('/role', 'UserController@getRole')->name('role');

  Route::resource('ambulance', 'AmbulanceController')->middleware('roles:admin|ambulance|hospital');

  Route::get('doctor/profile', 'DoctorController@doctorProfile')->name('doc_profile')->middleware('roles:doctor');
  Route::resource('doctor', 'DoctorController');
  //Route::post('doctor/profile', 'DoctorController@storeDoctorProfile')->name('sotre_doc_profile');

  Route::resource('seat', 'SeatController');

  Route::resource('seat', 'SeatController');

  Route::resource('hospital', 'HospitalController');

  // Route::get('/admin','Admin/DashboardController@home');

  Route::resource('education', 'EducationController');
  Route::resource('test', 'TestController');
  Route::resource('cost', 'CostController');

  //donor routes for admin
  Route::resource('/donor', 'DonorController')->middleware('roles:admin');

});

/*===========Start Visitor routes=================*/

Route::get('/find-ambulance', 'AllSearchController@ambulanceSearch')->name('find-amb');
Route::get('/find-donor', 'AllSearchController@donorSearch')->name('find-donor');

// Route::get('/amb_ajax','AllSearchController@ambulanceAjaxSearch' )->name('amb_ajax');
Route::get('/doctor_ajax','AllSearchController@doctorSearch' )->name('doc_search');

Route::get('/reg', function () {
    return view('visitor.donor_search');
});


Route::get('/test', function() {

});//api

/*===============End Visitor rotues===============*/


//visitor

Route::get('/', function () {
    return view('visitor.index');
});


Route::get('/a', function () {
    return view('visitor.ambsearch');
});


// Route::get('/b', function () {
//     return view('visitor.bsearch');
// });


Route::get('/d', function () {
    return view('visitor.hsearch');
});

Route::get('/do', function () {
    return view('visitor.dsearch');
});

// Route::get('/l', function () {
//     return view('visitor.login');
// });

// Route::get('/sa', function () {
//     return view('visitor.singleamb');
// });


Route::get('/sd', function () {
    return view('visitor.singledoctor');
});

Route::get('/sh', function () {
    return view('visitor.singlehospital');
});


// Route::get('/e', function () {
//     return view('visitor.education');
// });

// Route::get('/reg', function () {
//     return view('visitor.donor');
// });

//Blood donor Auths

Route::group(['prefix' => 'donor'], function () {
  Route::get('/login', 'DonorAuth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'DonorAuth\LoginController@login');
  Route::post('/logout', 'DonorAuth\LoginController@logout')->name('logout');

  Route::get('/register', 'DonorAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'DonorAuth\RegisterController@register');

  Route::post('/password/email', 'DonorAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'DonorAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'DonorAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'DonorAuth\ResetPasswordController@showResetForm');
});

//Dashboard auth routes
Route::group(['prefix' => 'dashboard'], function () {
  Route::get('/login', 'DashboardAuth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'DashboardAuth\LoginController@login');
  Route::post('/logout', 'DashboardAuth\LoginController@logout')->name('logout');

  Route::get('/register', 'DashboardAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'DashboardAuth\RegisterController@register');

  Route::post('/password/email', 'DashboardAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'DashboardAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'DashboardAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'DashboardAuth\ResetPasswordController@showResetForm');
});

app/Doctor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Doctor extends Model
{
    //
}

app/Http/Controllers/Admin/DoctorController.php
<?php

namespace App\Http\Controllers\Admin;
use Illuminate\Support\Facades\Session;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Doctor;
use App\User;
use Carbon\Carbon;
use Toastr;
//use App\Http\Requests\StoreAmbulance;

class DoctorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $doctors = Doctor::leftjoin('users', 'doctors.user_id', '=', 'users.id')->leftjoin('doctor_specialty', 'doctors.specialty_id', '=', 'doctor_specialty.id')->get();
        // $specialties = \DB::table('doctor_specialty')->all();
        // dd($doctors);        
        return view('admin.doctor.index', compact('doctors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('admin.doctor.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         
        //  $doctor = new Doctor();

        
        // $image = $request->file('image');
        // $slug = str_slug($request->email);

        // if (isset($image)) {

        //     $currentDate = Carbon::now()->toDateString();
            
        //     $image_name = $slug.'-'.$currentDate .uniqid(). '.' .$image->getClientOriginalExtension();
        //     if (!file_exists('image')) {
        //         mkdir('image', 0777, true);
        //     }
        //     $image->move('image',$image_name);
        // }

        // $doctor->name =$request->name;
        // $doctor->email =$request->email;
        // $doctor->address =$request->address;
        // $doctor->phone =$request->phone;
        // $doctor->degree =$request->degree;
        // $doctor->password =$request->password;
        // $doctor->specilities =$request->specilities;
        // $doctor->image = $image_name;
        // $doctor->save();

        // Session::flash('success','-------------Successfully registered-------------');
        // return redirect()->back();   
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        // return "assssdf";
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $doctor = User::join('doctors', 'doctors.user_id', '=', 'users.id')->where('doctors.user_id', $id)->first();
        $specialties = \DB::table('doctor_specialty')->get();

        return view('admin.doctor.edit', compact('doctor','specialties'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $doctor = Doctor::find($id);

        $doctor->designation =$request->designation;
        $doctor->specialty_id =$request->specialty_id;
        $doctor->degree =$request->degree;
        $doctor->chambers =$request->chambers;
        $doctor->degree =$request->degree;
        $doctor->longitude =$request->longitude;
        $doctor->latitude =$request->latitude;
        $doctor->save();  

        $user = User::find($request->user_id);

        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->show_pass = $request->password;
        $user->save();

        Toastr::success('Profile updated Successfully','message', ["positionClass" => "toast-bottom-right"]);

        return redirect()->back(); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         $doctor = doctor::find($id);
        $doctor->delete();

        Session::flash('delete', '.....Successfully deleted!....');
        return redirect()->back();
    }


    public function doctorProfile()
    {  
        $doctor = User::join('doctors', 'users.id', '=', 'doctors.user_id')->where('doctors.user_id', auth()->guard('dashboard')->id())->first();
        // dd($doctor);
        $specialties = \DB::table('doctor_specialty')->get();

        return view('admin.doctor.create', compact('doctor','specialties'));
    }

    //end class
}

resources/views/admin/doctor/create.blade.php
@extends('admin.layout.master')

@section('content')

        <div class="row mt">
          <!--  DATE PICKERS -->
          <div class="col-lg-12">
            <div class="form-panel">

              <div class="row">
	              <div class="col-md-6"><h4>Update Doctor Profile</h4></div>
	             <!--  <div class="col-md-6">
	              	<a class="btn btn-success pull-right" href="{{ route('doctor.index') }}"><i class="fa fa-list"></i> doctor List</a>
	              </div> -->
			  </div>
			   <hr>
              <div class="row">
    
	 	 		<form method="post" action="{{route('doctor.update', $doctor->id )}}" enctype="multipart/form-data">
	        	{{csrf_field()}}
				{{ method_field('PUT') }}
				
			    <div class="col-md-6">
					<input type="hidden" name="user_id" value="{{  $doctor->user_id }}">
				     <div class="form-group">
						  <label for="usr">Name:</label>
						  <input type="text" class="form-control" id="usr" value="{{ $doctor->name }}" name="name">
						  @if($errors->has('name'))
					      <span class="text-danger">
					        {{$errors->first('name')}}
					      </span>
					      @endif
					</div>
	                <div class="form-group">
					  <label for="sel1">E-mail:</label>
					  <input type="text" class="form-control" id="sel1" value="{{ $doctor->email }}" name="email">
						  @if($errors->has('email'))
					      <span class="text-danger">
					        {{$errors->first('email')}}
					      </span>
					      @endif
					</div>
					<div class="form-group">
					  <label for="pass">Password</label>
					  <input type="text" class="form-control" id="pass" value="{{ $doctor->show_pass }}" name="password">
						  @if($errors->has('password'))
					      <span class="text-danger">
					        {{$errors->first('password')}}
					      </span>
					      @endif
					</div>
					<div class="form-group">
					  <label for="longitude">Longitude</label>
					  <input type="text" class="form-control" id="longitude" value="{{ $doctor->longitude }}" name="longitude">
						  @if($errors->has('longitude'))
					      <span class="text-danger">
					        {{$errors->first('longitude')}}
					      </span>
					      @endif
					</div>
					<div class="form-group">
					  <label for="latitude">Latitude</label>
					  <input type="text" class="form-control" id="latitude" value="{{ $doctor->latitude }}" name="latitude">
						  @if($errors->has('latitude'))
					      <span class="text-danger">
					        {{$errors->first('latitude')}}
					      </span>
					      @endif
					</div>
					<div class="chamber-lacation">
		               <label for="user">Hospital Location:</label>
		                <input style="min-width:150 px; min-height: 50px;" id="pac-input" class="controls" type="text" placeholder="Search Box">
			           <div class="map" id="map">
			            
			           </div>
		        	</div>
		        	<!-- END GOOGLE MAP -->
			    </div>
				<div class="col-md-6">
					 <div class="form-group">
					  <label for="designation">Designation</label>
					  <input type="text" class="form-control" id="designation" value="{{ $doctor->designation }}" name="designation">
						  @if($errors->has('designation'))
					      <span class="text-danger">
					        {{$errors->first('designation')}}
					      </span>
					      @endif
					</div>
				
				<div class="form-group">
				  <label for="sel1">Specialties:</label>
					<select class="form-control" id="sel1" name="specialty_id">
						@foreach( $specialties as $specialty)
					    <option value="{{ $specialty->id }}" {{ $specialty->id == $doctor->specialty_id ? "selected": ""}}>{{ $specialty->specialty_name }}</option>
						@endforeach
					</select>
				</div>

					<div class="form-group">
					  <label for="degree">Degree</label>
					  <input type="text" class="form-control" id="degree" value="{{ $doctor->degree }}" name="degree">
						  @if($errors->has('degree'))
					      <span class="text-danger">
					        {{$errors->first('degree')}}
					      </span>
					      @endif
					</div>
					<div class="form-group">
					  <label for="chambers">Chambers name & Location</label>
					  <textarea name="chambers" class="form-control" placeholder="Chambers Details"> {{ $doctor->chambers }}</textarea>
						  @if($errors->has('chambers'))
					      <span class="text-danger">
					        {{$errors->first('chambers')}}
					      </span>
					      @endif
					</div>
				</div>
				<hr>
				<div class="col-md-12 mt">
					 <div class="form-group">
						  <button type="submit" class="btn btn-success">Update Profile</button>
					</div>
				</div>
			 </form>
			</div>
		</div>
	</div>
</div>
@stop


@push('script')
<script type="text/javascript">
  $(function () {

    $('.select2').select2();

  });
</script>


<script type="text/javascript">

     function initAutocomplete() {
     	var myLatLng = {lat: {{ $doctor->latitude }}, lng: {{$doctor->longitude }} };

        var map = new google.maps.Map(document.getElementById('map'), {
          center: myLatLng,
          zoom: 15,
          mapTypeId: 'roadmap'
        });

         var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });


        google.maps.event.addListener(map,'click',function(event){
        	document.getElementById('latitude').value=event.latLng.lat()
        	document.getElementById('longitude').value=event.latLng.lng()
        })
        // Create the search box and link it to the UI element.
        var input = document.getElementById('pac-input');
        var searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        // Bias the SearchBox results towards current map's viewport.
        map.addListener('bounds_changed', function() {
          searchBox.setBounds(map.getBounds());
        });

        var markers = [];
        // Listen for the event fired when the user selects a prediction and retrieve
        // more details for that place.
        searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();

          if (places.length == 0) {
            return;
          }

          // Clear out the old markers.
          markers.forEach(function(marker) {
            marker.setMap(null);
          });
          markers = [];

          // For each place, get the icon, name and location.
          var bounds = new google.maps.LatLngBounds();
          places.forEach(function(place) {
            if (!place.geometry) {
              console.log("Returned place contains no geometry");
              return;
            }
            var icon = {
              url: place.icon,
              size: new google.maps.Size(71, 71),
              origin: new google.maps.Point(0, 0),
              anchor: new google.maps.Point(17, 34),
              scaledSize: new google.maps.Size(25, 25)
            };

            // Create a marker for each place.
            markers.push(new google.maps.Marker({
              map: map,
              icon: icon,
              title: place.name,
              position: place.geometry.location
            }));

            if (place.geometry.viewport) {
              // Only geocodes have viewport.
              bounds.union(place.geometry.viewport);
            } else {
              bounds.extend(place.geometry.location);
            }
          });
          map.fitBounds(bounds);
        });
      }

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCih3jBa9TL9vizjOb2zyHCY9yD0sdpeIo&libraries=places&callback=initAutocomplete"
         async defer></script>

@endpush

resources/views/admin/doctor/edit.blade.php
@extends('admin.layout.master')

@section('content')

        <div class="row mt">
          <!--  DATE PICKERS -->
          <div class="col-lg-12">
            <div class="form-panel">

              <div class="row">
	              <div class="col-md-6"><h4>Update Doctor Profile</h4></div>
	              <div class="col-md-6">
	              	<a class="btn btn-success pull-right" href="{{ route('doctor.index') }}"><i class="fa fa-list"></i> Doctor List</a>
	              </div>
			  </div>
			   <hr>
              <div class="row">
    
	 	 		<form method="post" action="{{route('doctor.update', $doctor->id )}}" enctype="multipart/form-data">
	        	{{csrf_field()}}
				{{ method_field('PUT') }}
				
			    <div class="col-md-6">
					<input type="hidden" name="user_id" value="{{  $doctor->user_id }}">
				     <div class="form-group">
						  <label for="usr">Name:</label>
						  <input type="text" class="form-control" id="usr" value="{{ $doctor->name }}" name="name">
						  @if($errors->has('name'))
					      <span class="text-danger">
					        {{$errors->first('name')}}
					      </span>
					      @endif
					</div>
	                <div class="form-group">
					  <label for="sel1">E-mail:</label>
					  <input type="text" class="form-control" id="sel1" value="{{ $doctor->email }}" name="email">
						  @if($errors->has('email'))
					      <span class="text-danger">
					        {{$errors->first('email')}}
					      </span>
					      @endif
					</div>
					<div class="form-group">
					  <label for="pass">Password</label>
					  <input type="text" class="form-control" id="pass" value="{{ $doctor->show_pass }}" name="password">
						  @if($errors->has('password'))
					      <span class="text-danger">
					        {{$errors->first('password')}}
					      </span>
					      @endif
					</div>
					<div class="form-group">
					  <label for="longitude">Longitude</label>
					  <input type="text" class="form-control" id="longitude" value="{{ $doctor->longitude }}" name="longitude">
						  @if($errors->has('longitude'))
					      <span class="text-danger">
					        {{$errors->first('longitude')}}
					      </span>
					      @endif
					</div>
					<div class="form-group">
					  <label for="latitude">Latitude</label>
					  <input type="text" class="form-control" id="latitude" value="{{ $doctor->latitude }}" name="latitude">
						  @if($errors->has('latitude'))
					      <span class="text-danger">
					        {{$errors->first('latitude')}}
					      </span>
					      @endif
					</div>
					<div class="chamber-lacation">
		               <label for="user">Doctor Location:</label>
		                <input style="min-width:150 px; min-height: 50px;" id="pac-input" class="controls" type="text" placeholder="Search Box">
			           <div class="map" id="map">
			            
			           </div>
		        	</div>
		        	<!-- END GOOGLE MAP -->
			    </div>
				<div class="col-md-6">
					 <div class="form-group">
					  <label for="designation">Designation</label>
					  <input type="text" class="form-control" id="designation" value="{{ $doctor->designation }}" name="designation">
						  @if($errors->has('designation'))
					      <span class="text-danger">
					        {{$errors->first('designation')}}
					      </span>
					      @endif
					</div>
				<div class="form-group">
				  <label for="sel1">Specialties:</label>
					<select class="form-control" id="sel1" name="specialty_id">
						@foreach( $specialties as $specialty)
					    <option value="{{ $specialty->id }}" {{ $specialty->id == $doctor->specialty_id ? "selected": ""}}>{{ $specialty->specialty_name }}</option>
						@endforeach
					</select>
				</div>
					<div class="form-group">
					  <label for="degree">Degree</label>
					  <input type="text" class="form-control" id="degree" value="{{ $doctor->degree }}" name="degree">
						  @if($errors->has('degree'))
					      <span class="text-danger">
					        {{$errors->first('degree')}}
					      </span>
					      @endif
					</div>
					<div class="form-group">
					  <label for="chambers">Chambers name & Location</label>
					  <textarea name="chambers" class="form-control" placeholder="Chambers Details"> {{ $doctor->chambers }}</textarea>
						  @if($errors->has('chambers'))
					      <span class="text-danger">
					        {{$errors->first('chambers')}}
					      </span>
					      @endif
					</div>
				</div>
				<hr>
				<div class="col-md-12 mt">
					 <div class="form-group">
						  <button type="submit" class="btn btn-success">Update Profile</button>
					</div>
				</div>
			 </form>
			</div>
		</div>
	</div>
</div>
@stop


@push('script')
<script type="text/javascript">
  $(function () {

    $('.select2').select2();

  });
</script>


<script type="text/javascript">

     function initAutocomplete() {
     	var myLatLng = {lat: {{ $doctor->latitude }}, lng: {{$doctor->longitude }} };

        var map = new google.maps.Map(document.getElementById('map'), {
          center: myLatLng,
          zoom: 15,
          mapTypeId: 'roadmap'
        });

         var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });


        google.maps.event.addListener(map,'click',function(event){
        	document.getElementById('latitude').value=event.latLng.lat()
        	document.getElementById('longitude').value=event.latLng.lng()
        })
        // Create the search box and link it to the UI element.
        var input = document.getElementById('pac-input');
        var searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        // Bias the SearchBox results towards current map's viewport.
        map.addListener('bounds_changed', function() {
          searchBox.setBounds(map.getBounds());
        });

        var markers = [];
        // Listen for the event fired when the user selects a prediction and retrieve
        // more details for that place.
        searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();

          if (places.length == 0) {
            return;
          }

          // Clear out the old markers.
          markers.forEach(function(marker) {
            marker.setMap(null);
          });
          markers = [];

          // For each place, get the icon, name and location.
          var bounds = new google.maps.LatLngBounds();
          places.forEach(function(place) {
            if (!place.geometry) {
              console.log("Returned place contains no geometry");
              return;
            }
            var icon = {
              url: place.icon,
              size: new google.maps.Size(71, 71),
              origin: new google.maps.Point(0, 0),
              anchor: new google.maps.Point(17, 34),
              scaledSize: new google.maps.Size(25, 25)
            };

            // Create a marker for each place.
            markers.push(new google.maps.Marker({
              map: map,
              icon: icon,
              title: place.name,
              position: place.geometry.location
            }));

            if (place.geometry.viewport) {
              // Only geocodes have viewport.
              bounds.union(place.geometry.viewport);
            } else {
              bounds.extend(place.geometry.location);
            }
          });
          map.fitBounds(bounds);
        });
      }

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCih3jBa9TL9vizjOb2zyHCY9yD0sdpeIo&libraries=places&callback=initAutocomplete"
         async defer></script>

@endpush

resources/views/admin/doctor/index.blade.php
@extends('admin.layout.master')


@section('content')

    <div class="row mt">
      <div class="col-md-12">
        <div class="content-panel" style="padding: 10px;">
          <div class="row" style="padding: 10px;" >
              <div class="col-md-6">
                  <h4>All Doctors</h4>
              </div>
              <div class="col-md-6">
                <a href="{{ route('user.create') }}" class="btn btn-sm btn-info pull-right"><i class="fa fa-plus"></i> Add doctor admin</a>
              </div>
          </div>
        
         <table  id="example1" class="table table-bordered table-hover">
            <thead>
              <tr>
                <th>SL#</th>

                <th>Name</th>
                <th>E-mail</th>
                <th>Designation</th>
                <th>Specialities</th>
                <th>Degree</th>
                <th>Chamber</th>
                <th>Action</th>
              </tr>
            </thead>        
            <tbody>
              @if($doctors)
                 @foreach($doctors as $key => $doctor)
              <tr>
                <td>{{ $key+1 }}</td>
                <td>{{ $doctor->name }}</td>
                <td>{{ $doctor->email }}</td>
                <td>{{ $doctor->designation }}</td>
                <td>{{ $doctor->specialty_name }}</td>
                <td>{{ $doctor->degree }}</td>
                <td>{{ $doctor->chambers }}</td>
                <td>
                  <a class="btn btn-info btn-sm" href="{{ route('doctor.edit', $doctor->user_id) }}"><i class="fa fa-edit "></i></a>
                  <form id="delete-form-{{ $doctor->id }}" action="{{ route('doctor.destroy',$doctor->id) }}" style="display: none;" method="POST">
                      {{csrf_field()}}
                      {{ method_field('DELETE') }}
                  </form>
                  <button type="button" class="btn btn-danger btn-sm" title="Delete" onclick="if(confirm('Are you sure? You want to delete this?')){
                      event.preventDefault();
                      document.getElementById('delete-form-{{ $doctor->id }}').submit();
                  }else {
                      event.preventDefault();
                          }"><i class="fa fa-trash-o"></i>
                  </button>

                </td>
              </tr>
             @endforeach
             @endif
            </tbody>
          </table>
        </div>
        <!-- /content-panel -->
      </div>
      <!-- /col-md-12 -->
    </div>
@stop

@push('script')
<script type="text/javascript">
  $(function () {
    //$('#example1').DataTable();
    $('#example1').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    });
  });
</script>
@endpush