routes/dashboard.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('dashboard')->user();

    // dd($users);

    return view('admin.dashboard');
})->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/', function () {
//     return view('welcome');
// });


// Route::get('/search/{search}',function($search){
// 	return App\Hospital::where('hname','like','%'.$search.'%')->pluck('hname')->toArray();
// });




// //doctor
// Route::get('/doctor', function () {
//     return view('admin.doctor.create');
// });
// Route::get('/doctor/edit', function () {
//     return view('admin.doctor.edit');
// });

// //
// //hospital

// Route::get('/hospital', function () {
//     return view('admin.hospital.create');
// });
// Route::get('/hospital/edit', function () {
//     return view('admin.hospital.edit');
// });
// use Illuminate\Support\Facades\Auth;

// //auth routes
// Auth::routes();


Route::group(['prefix'=>'dashboard', 'middleware'=>'dashboard', 'namespace'=>'Admin'], function(){
    

  Route::get('/', 'DashboardController@index')->name('admin.dashboard');

  // Route::resource('categories', 'CategoryController');

  Route::resource('user', 'UserController');
  Route::get('/role', 'UserController@getRole')->name('role');

  Route::resource('ambulance', 'AmbulanceController')->middleware('roles:admin|ambulance|hospital');

  Route::get('doctor/profile', 'DoctorController@doctorProfile')->name('doc_profile')->middleware('roles:doctor');
  Route::resource('doctor', 'DoctorController');
  //Route::post('doctor/profile', 'DoctorController@storeDoctorProfile')->name('sotre_doc_profile');

  Route::resource('seat', 'SeatController');

  Route::resource('seat', 'SeatController');

  Route::resource('hospital', 'HospitalController');

  // Route::get('/admin','Admin/DashboardController@home');

  Route::resource('education', 'EducationController');
  Route::resource('test', 'TestController');
  Route::resource('cost', 'CostController');

  //donor routes for admin
  Route::resource('/donor', 'DonorController')->middleware('roles:admin');

});

/*===========Start Visitor routes=================*/

Route::get('/find-ambulance', 'AllSearchController@ambulanceSearch')->name('find-amb');
Route::get('/find-donor', 'AllSearchController@donorSearch')->name('find-donor');

// Route::get('/amb_ajax','AllSearchController@ambulanceAjaxSearch' )->name('amb_ajax');
Route::get('/doctor_ajax','AllSearchController@doctorSearch' )->name('doc_search');

Route::get('/reg', function () {
    return view('visitor.donor_search');
});


Route::get('/test', function() {

});//api

/*===============End Visitor rotues===============*/


//visitor

Route::get('/', function () {
    return view('visitor.index');
});


Route::get('/a', function () {
    return view('visitor.ambsearch');
});


// Route::get('/b', function () {
//     return view('visitor.bsearch');
// });


Route::get('/d', function () {
    return view('visitor.hsearch');
});

Route::get('/do', function () {
    return view('visitor.dsearch');
});

// Route::get('/l', function () {
//     return view('visitor.login');
// });

// Route::get('/sa', function () {
//     return view('visitor.singleamb');
// });


Route::get('/sd', function () {
    return view('visitor.singledoctor');
});

Route::get('/sh', function () {
    return view('visitor.singlehospital');
});


// Route::get('/e', function () {
//     return view('visitor.education');
// });

// Route::get('/reg', function () {
//     return view('visitor.donor');
// });

//Blood donor Auths

Route::group(['prefix' => 'donor'], function () {
  Route::get('/login', 'DonorAuth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'DonorAuth\LoginController@login');
  Route::post('/logout', 'DonorAuth\LoginController@logout')->name('logout');

  Route::get('/register', 'DonorAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'DonorAuth\RegisterController@register');

  Route::post('/password/email', 'DonorAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'DonorAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'DonorAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'DonorAuth\ResetPasswordController@showResetForm');
});

//Dashboard auth routes
Route::group(['prefix' => 'dashboard'], function () {
  Route::get('/login', 'DashboardAuth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'DashboardAuth\LoginController@login');
  Route::post('/logout', 'DashboardAuth\LoginController@logout')->name('logout');

  Route::get('/register', 'DashboardAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'DashboardAuth\RegisterController@register');

  Route::post('/password/email', 'DashboardAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'DashboardAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'DashboardAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'DashboardAuth\ResetPasswordController@showResetForm');
});

app/Education.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Education extends Model
{
    protected $fillable=['vname','vlink'];
}

app/Http/Controllers/Admin/EducationController.php
<?php

namespace App\Http\Controllers\Admin;
use Illuminate\Support\Facades\Session;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Education;
use Carbon\Carbon;
use App\Http\Requests\StoreEducation;
use Toastr;


class EducationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view ('admin.education.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view ('admin.education.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $education = new Education();
        
        $education->vname =$request->vname;
        $education->vlink =$request->vlink;
        $education->save();

        // Session::flash('success','-------------Successfully registered-------------');
        Toastr::success('Successfully Added', '', [ "positionClass" => "toast-top-center", "closeButton"=> true, "progressBar"=> true]);

        return redirect()->back();   
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/Education/create.blade.php
@extends('admin.layout.master')


@section('content')


<div class="container" style="width: 100%;">
  <h2 style="margin-left: 30px;">Add Video</h2>
  <hr>
  <br>
  
    <div class="row">
<!-- 
       @if(Session::has('success'))
              <div class="">
                <h5 style="color: green; ;margin-left: 15px; margin-top: -1px;"> {{Session::get('success')}}</h5> 
              </div>
              @endif -->

    <form method="post" action="{{route('education.store')}}" enctype="multipart/form-data">
          {{csrf_field()}}

      <div class="col-md-6">

      <div class="form-group">
          <label for="user">Video Type or Name:</label>
          <input type="text" class="form-control" id="Name" value="{{old('vname')}}" name="vname">
      </div>                       
                                
       <div class="btn-group">
          <br>
        <button type="submit" class="btn btn-success">Submit</button>
        <button type="reset" class="btn btn-primary">Reset</button>
          
        </div>

    </div>

       
    <div class="col-md-6">
        

      <div class="form-group">
          <label for="user">Video Link:</label>
          <input type="text" class="form-control" id="Phondde" value="{{old('vlink')}}" name="vlink">
      </div>
          
    </div>            
    </form>

    </div>  

</div>          
@stop

resources/views/admin/Education/edit.blade.php
@extends('admin.layout.master')


@section('content')


<div class="container" style="width: 100%;">
	<h2 style="margin-left: 30px;">Update Hospital Profile</h2>
	<hr>
	<br>
  
 	 	<div class="row">
<!-- 
 	 		 @if(Session::has('success'))
              <div class="">
                <h5 style="color: green; ;margin-left: 15px; margin-top: -1px;"> {{Session::get('success')}}</h5> 
              </div>
              @endif -->

 	 		<form method="post" action=" " enctype="multipart/form-data">
        	{{csrf_field()}}

	    <div class="col-md-6">

			<div class="form-group">
				  <label for="user">Hospital Name:</label>
				  <input type="text" class="form-control" id="Name" name="hname">
			</div>

			<div class="form-group">
				  <label for="user">User Name:</label>
				  <input type="text" class="form-control" id="Name" name="hname">
			</div>         
		    

		    <div class="form-group">
				  <label for="user">Email:</label>
				  <input type="email" class="form-control" id="Email" name="email">
			</div>

         	<div class="form-group">
				  <label for="user">Address:</label>
				  <input type="address" class="form-control" id="address" name="address">
			</div>
              
			<div class="radio">
				<label class="radio-inline"><input type="radio" name="optradio" checked>Active</label>
				<label class="radio-inline"><input type="radio" name="optradio">De-Active</label>
    		</div>
			
			

			 <div class="btn-group">
         	<br>
			  <button type="submit" class="btn btn-success">Submit</button>
			  <button type="reset" class="btn btn-primary">Reset</button>
				  
		    </div>

		</div>


        
		<div class="col-md-6">

			<div class="form-group">
				  <label for="user">Phone Number:</label>
				  <input type="number" class="form-control" id="Phone" name="phone">
			</div>	

			<div class="form-group">
				  <label for="user">Alternative Phone Number:</label>
				  <input type="number" class="form-control" id="Phone" name="phone">
			</div>	 	
			 

			<div class="form-group">
				  <label for="user">Password:</label>
				  <input type="password" class="form-control" id="pwd" name="password">
			</div>
			<div class="form-group">
				  <label for="user">Image:</label>
				  <input type="file"  id="usr" value="{{old('image')}}" name="image">
			</div>

		      
		</div>
  		
  		
		</form>

		


		</div>	

</div>			    




@stop

resources/views/admin/Education/index.blade.php
@extends('admin.layout.master')


@section('content')
<?php $i=0;?>
<button onclick="getDistances()">Get Distances</button>
<div id="suggestions"></div>
<input type="text" onkeyup="getSuggestions(this)">
@foreach($hospitals as $hospital)
Name: {{$hospital->hname}}
Distance: <div id="distance{{$i}}"></div>

<?php $i++; ?>
@endforeach
<h1 id='distan' style="font-size: 50px"></p>





@stop
@section('scripts')
<script type="text/javascript">
  function getDistances(){
    if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };

           
            console.log(pos)
            axios.post('/test',{
              latitude: pos.lat,
              longitude: pos.lng
            }).then((res)=>{
               // document.getElementById('distan').innerHTML=res.data
                res.data.forEach(function(value,index){
                   document.getElementById('distance'+index).innerHTML=value
                })
            })
          }, function() {
          
          });
        } else {
          // Browser doesn't support Geolocation
        
        }
  

  }
  function getSuggestions(element){
    axios.get('/search/'+element.value)
    .then(function(response){
      console.log(response.data)
      response.data.forEach(function(element){
        $('#suggestions').append('<p>'+element+'</p>')
      })
    })
  }
     
</script>

@stop