routes/dashboard.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('dashboard')->user();

    // dd($users);

    return view('admin.dashboard');
})->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/', function () {
//     return view('welcome');
// });


// Route::get('/search/{search}',function($search){
// 	return App\Hospital::where('hname','like','%'.$search.'%')->pluck('hname')->toArray();
// });




// //doctor
// Route::get('/doctor', function () {
//     return view('admin.doctor.create');
// });
// Route::get('/doctor/edit', function () {
//     return view('admin.doctor.edit');
// });

// //
// //hospital

// Route::get('/hospital', function () {
//     return view('admin.hospital.create');
// });
// Route::get('/hospital/edit', function () {
//     return view('admin.hospital.edit');
// });
// use Illuminate\Support\Facades\Auth;

// //auth routes
// Auth::routes();


Route::group(['prefix'=>'dashboard', 'middleware'=>'dashboard', 'namespace'=>'Admin'], function(){
    

  Route::get('/', 'DashboardController@index')->name('admin.dashboard');

  // Route::resource('categories', 'CategoryController');

  Route::resource('user', 'UserController');
  Route::get('/role', 'UserController@getRole')->name('role');

  Route::resource('ambulance', 'AmbulanceController')->middleware('roles:admin|ambulance|hospital');

  Route::get('doctor/profile', 'DoctorController@doctorProfile')->name('doc_profile')->middleware('roles:doctor');
  Route::resource('doctor', 'DoctorController');
  //Route::post('doctor/profile', 'DoctorController@storeDoctorProfile')->name('sotre_doc_profile');

  Route::resource('seat', 'SeatController');

  Route::resource('seat', 'SeatController');

  Route::resource('hospital', 'HospitalController');

  // Route::get('/admin','Admin/DashboardController@home');

  Route::resource('education', 'EducationController');
  Route::resource('test', 'TestController');
  Route::resource('cost', 'CostController');

  //donor routes for admin
  Route::resource('/donor', 'DonorController')->middleware('roles:admin');

});

/*===========Start Visitor routes=================*/

Route::get('/find-ambulance', 'AllSearchController@ambulanceSearch')->name('find-amb');
Route::get('/find-donor', 'AllSearchController@donorSearch')->name('find-donor');

// Route::get('/amb_ajax','AllSearchController@ambulanceAjaxSearch' )->name('amb_ajax');
Route::get('/doctor_ajax','AllSearchController@doctorSearch' )->name('doc_search');

Route::get('/reg', function () {
    return view('visitor.donor_search');
});


Route::get('/test', function() {

});//api

/*===============End Visitor rotues===============*/


//visitor

Route::get('/', function () {
    return view('visitor.index');
});


Route::get('/a', function () {
    return view('visitor.ambsearch');
});


// Route::get('/b', function () {
//     return view('visitor.bsearch');
// });


Route::get('/d', function () {
    return view('visitor.hsearch');
});

Route::get('/do', function () {
    return view('visitor.dsearch');
});

// Route::get('/l', function () {
//     return view('visitor.login');
// });

// Route::get('/sa', function () {
//     return view('visitor.singleamb');
// });


Route::get('/sd', function () {
    return view('visitor.singledoctor');
});

Route::get('/sh', function () {
    return view('visitor.singlehospital');
});


// Route::get('/e', function () {
//     return view('visitor.education');
// });

// Route::get('/reg', function () {
//     return view('visitor.donor');
// });

//Blood donor Auths

Route::group(['prefix' => 'donor'], function () {
  Route::get('/login', 'DonorAuth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'DonorAuth\LoginController@login');
  Route::post('/logout', 'DonorAuth\LoginController@logout')->name('logout');

  Route::get('/register', 'DonorAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'DonorAuth\RegisterController@register');

  Route::post('/password/email', 'DonorAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'DonorAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'DonorAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'DonorAuth\ResetPasswordController@showResetForm');
});

//Dashboard auth routes
Route::group(['prefix' => 'dashboard'], function () {
  Route::get('/login', 'DashboardAuth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'DashboardAuth\LoginController@login');
  Route::post('/logout', 'DashboardAuth\LoginController@logout')->name('logout');

  Route::get('/register', 'DashboardAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'DashboardAuth\RegisterController@register');

  Route::post('/password/email', 'DashboardAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'DashboardAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'DashboardAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'DashboardAuth\ResetPasswordController@showResetForm');
});

app/Donor.php
<?php

namespace App;

use App\Notifications\DonorResetPassword;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Donor extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    // protected $fillable = [
    //     'name', 'email', 'password',
    // ];
    protected $guarded = [];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new DonorResetPassword($token));
    }
}

app/Http/Controllers/Admin/DonorController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Donor;

class DonorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $donors = Donor::orderBy('id','desc')->get();
        return view('admin.donor.index', compact('donors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $donor = Donor::find($id);
        $donor->delete();

        Toastr::success('Donor Successfully deleted!','message', ["positionClass" => "toast-bottom-right"]);
        return redirect()->back();
    }
}

resources/views/admin/donor/create.blade.php
@extends('admin.layout.master')

@section('content')

        <div class="row mt">
          <!--  DATE PICKERS -->
          <div class="col-lg-12">
            <div class="form-panel">

              <div class="row">
	              <div class="col-md-6"><h4>Add user</h4></div>
	              <div class="col-md-6">
	              	<a class="btn btn-success pull-right" href="{{ route('user.index') }}"><i class="fa fa-list"></i> User List</a>
	              </div>
			  </div>
			   <hr>
              <div class="row">
    
	 	 		<form method="post" action="{{route('user.store')}}" enctype="multipart/form-data">
	        	{{csrf_field()}}
	        	
			    <div class="col-md-6">
					 <div class="form-group">
						  <label for="name">Name:</label>
						  <input type="text" class="form-control" id="name" value="{{old('name')}}" name="name">
						  @if($errors->has('name'))
					      <span class="text-danger">
					        {{$errors->first('name')}}
					      </span>
					      @endif
					</div>

				     <div class="form-group">
						  <label for="usr">E-mail:</label>
						  <input type="email" class="form-control" id="usr" value="{{ old('email') }}" name="email">
						  @if($errors->has('email'))
					      <span class="text-danger">
					        {{$errors->first('email')}}
					      </span>
					      @endif
					</div>
			    </div>
				<div class="col-md-6">
					 <div class="form-group">
						  <label for="pass">Password:</label>
						  <input type="text" class="form-control" id="pass" value="{{old('password')}}" name="password">
						  @if($errors->has('password'))
					      <span class="text-danger">
					        {{$errors->first('password')}}
					      </span>
					      @endif
					</div>

					 <div class="form-group">
						  <label for="roles">Select Role:</label>
						  <select name="role" id="roles" class="form-control" required>
						  		<option disabled selected>Choose role</option>
                            @foreach($roles as $role)
							
                                <option value="{{ $role->id }}">{{ $role->name }}</option>

                            @endforeach
                        </select>
					</div>
				</div>
				<hr>
				<div class="col-md-12">
					 <div class="form-group">
						  <button type="submit" class="btn btn-success">Add</button>
						  <button type="reset" class="btn btn-primary">Reset</button>
					</div>
				</div>
			 </form>
			</div>
		</div>
	</div>
</div>
@stop


@push('script')
<script type="text/javascript">
  $(function () {

    $('.select2').select2();

  });
</script>
@endpush

resources/views/admin/donor/edit.blade.php
@extends('admin.layout.master')

@section('content')

        <div class="row mt">
          <!--  DATE PICKERS -->
          <div class="col-lg-12">
            <div class="form-panel">

              <div class="row">
	              <div class="col-md-6"><h4>Update user</h4></div>
	              <div class="col-md-6">
	              	<a class="btn btn-success pull-right" href="{{ route('user.index') }}"><i class="fa fa-list"></i> User List</a>
	              </div>
			  </div>
			   <hr>
              <div class="row">
    
	 	 		<form method="post" action="{{ route('user.update', $user->id )}}" enctype="multipart/form-data">
	        	
	        	{{ method_field('PUT') }}
	        	{{csrf_field()}}
	        	
			    <div class="col-md-6">
					 <div class="form-group">
						  <label for="name">Name:</label>
						  <input type="text" class="form-control" id="name" value="{{ $user->name }}" name="name">
						  @if($errors->has('name'))
					      <span class="text-danger">
					        {{$errors->first('name')}}
					      </span>
					      @endif
					</div>

				     <div class="form-group">
						  <label for="usr">E-mail:</label>
						  <input type="email" class="form-control" id="usr" value="{{  $user->email  }}" name="email" readonly>
						  @if($errors->has('email'))
					      <span class="text-danger">
					        {{$errors->first('email')}}
					      </span>
					      @endif
					</div>
			    </div>
				<div class="col-md-6">
					 <div class="form-group">
						  <label for="pass">Password:</label>
						  <input type="text" class="form-control" id="pass" value="{{ $user->show_pass }}" name="password">
						  @if($errors->has('password'))
					      <span class="text-danger">
					        {{$errors->first('password')}}
					      </span>
					      @endif
					</div>

					 <div class="form-group">
						  <label for="roles">Select Role:</label>
						  <select name="role" id="roles" class="form-control" required>
                            <option disabled selected>Choose role</option>
                            
                             @foreach($roles as $role)

                                <option value="{{ $role->id }}"  

                                	@if(isset($user_role[0]['id']) && $user_role[0]['id'] == $role->id) 
									{{ 'selected'}}
									@endif
                                	>{{ $role->name }}</option>
                             @endforeach
                            
                        </select>
					</div>
				</div>
				<hr>
				<div class="col-md-12">
					 <div class="form-group">
						  <button type="submit" class="btn btn-success">Update</button>
					</div>
				</div>
			 </form>
			</div>
		</div>
	</div>
</div>
@stop


@push('script')
<script type="text/javascript">
  $(function () {

    $('.select2').select2();

  });
</script>
@endpush

resources/views/admin/donor/index.blade.php
@extends('admin.layout.master')


@section('content')


<div class="row mt">
      <div class="col-md-12">
        <div class="content-panel" style="padding: 10px;">
          <div class="row" style="padding: 10px;" >
              <div class="col-md-6">
                  <h4>All Registered Donor</h4>
              </div>
          </div>
         <table  id="example1" class="table table-bordered table-hover">
                <thead>
                  <tr>
                    <th><i class="fa fa-bullhorn"></i> SL#</th>
                    <th>Name</th>
                    <th>E-mail</th>
                    <th>DOB</th>
                    <th>District</th>
                    <th>Last donation</th>
                    <th>Phone</th>
                    <th>Address</th>
                    <th>Action</th>
                  </tr>
                </thead>
                
                <tbody>
                  @php
                      $i=0;
                  @endphp
                	@foreach($donors as $donor)
                     @php
                        $i++;
                    @endphp
                  <tr>
                    <td>
                      {{ $i }}
                    </td>
                    <td>{{ $donor->name }}</td>
                    <td >{{ $donor->email }}</td>
                    <td>{{ $donor->dob }}</td>
                    <td>{{ $donor->district }}</td>
                    <td>{{ $donor->ldt }}</td>
                    <td>{{ $donor->number }}</td>
                    <td>{{ $donor->address }}</td>
                    <td>
                      <a class="btn btn-info btn-sm" href="{{ route('donor.edit', $donor->id) }}"><i class="fa fa-edit "></i></a>

                    <form id="delete-form-{{ $donor->id }}" action="{{ route('donor.destroy',$donor->id) }}" style="display: none;" method="POST">
                        {{csrf_field()}}
                        {{ method_field('DELETE') }}
                    </form>
                    <button type="button" class="btn btn-danger btn-sm" title="Delete" onclick="if(confirm('Are you sure? You want to delete this?')){
                        event.preventDefault();
                        document.getElementById('delete-form-{{ $donor->id }}').submit();
                    }else {
                        event.preventDefault();
                            }"><i class="fa fa-trash-o"></i>
                    </button>
                    
                    </td>
                  </tr>
                 @endforeach           
            </tbody>
        </div>
        <!-- /content-panel -->
      </div>
      <!-- /col-md-12 -->
    </div>
@stop

@push('script')
<script type="text/javascript">
  $(function () {
    //$('#example1').DataTable();
    $('#example1').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    });
  });
</script>
@endpush